name: Custom Toolchain ID (single version)
on:
  workflow_dispatch:
  

jobs:
  custom-id-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java with custom toolchain ID
        uses: priya-kinthali/setup-java@update-gradle-cache-docs
        with:
          distribution: temurin
          java-version: '11'
          mvn-toolchain-id: 'some_other_id'
          # mvn-toolchain-vendor: 'Eclipse Temurin'
      - name: Inspect toolchains
        run: cat ~/.m2/toolchains.xml
