name: Custom Toolchain ID (single version)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  custom-id-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java with custom toolchain ID
        uses: guicamest/setup-java@feat/669/support_sdkmanrc
        with:
          distribution: temurin
          java-version: '11'
          mvn-toolchain-id: 'some_other_id'
          # mvn-toolchain-vendor: 'Eclipse Temurin'
      - name: Inspect toolchains
        run: cat ~/.m2/toolchains.xml
